import type { CallRecord } from "@/lib/domain/types";

type Seed = Omit<CallRecord, "startedAt"> & { minutesAgo: number };

/**
 * Hand-written, realistic calls. `minutesAgo` is resolved against "now" so the
 * demo always looks live.
 */
const SEEDS: Seed[] = [
  {
    id: "call_7Q2K",
    minutesAgo: 9,
    durationSec: 154,
    direction: "inbound",
    caller: { name: "Nathalie Garnier", phone: "06 12 48 77 31", known: true },
    siteId: "lyon-est",
    language: "fr",
    intent: "rdv_atelier",
    outcome: "rdv_pris",
    sentiment: "positif",
    afterHours: false,
    csat: 5,
    vehicle: { make: "Peugeot", model: "3008 Hybrid", plate: "GH-482-TL", year: 2021, mileage: 61200 },
    appointmentId: "apt_1001",
    summary:
      "Cliente connue, révision des 60 000 km sur 3008 Hybrid. RDV pris jeudi 8h30 avec véhicule de courtoisie. SMS de confirmation envoyé.",
    extracted: { Service: "Révision constructeur", Véhicule: "Peugeot 3008 Hybrid · GH-482-TL", Kilométrage: "61 200 km", Créneau: "Jeudi 8h30", Courtoisie: "Oui" },
    transcript: [
      { role: "agent", t: 0, text: "Mistral Automobiles bonjour, je suis Léa, l'assistante de la concession. Comment puis-je vous aider ?" },
      { role: "caller", t: 5, text: "Bonjour, je voudrais prendre rendez-vous pour la révision de ma 3008, elle arrive aux 60 000." },
      { role: "tool", t: 8, text: "Client identifié via le numéro appelant", tool: { name: "lookup_customer", input: { phone: "0612487731" }, result: { name: "Nathalie Garnier", vehicle: "Peugeot 3008 Hybrid GH-482-TL" } } },
      { role: "agent", t: 9, text: "Bien sûr madame Garnier. Je vois votre 3008 Hybrid immatriculée GH-482-TL. Vous êtes bien à environ 60 000 kilomètres ?" },
      { role: "caller", t: 16, text: "Oui, 61 200 exactement. Et il faudrait que j'aie une voiture, je travaille." },
      { role: "tool", t: 19, text: "Recherche de créneaux · révision + courtoisie", tool: { name: "check_availability", input: { service: "Révision constructeur", courtesy_vehicle: true }, result: { slots: ["Jeudi 8h30", "Vendredi 8h00", "Lundi 9h15"] } } },
      { role: "agent", t: 21, text: "Pour une révision avec véhicule de courtoisie, je peux vous proposer jeudi à 8h30, vendredi à 8h, ou lundi à 9h15. Qu'est-ce qui vous arrange ?" },
      { role: "caller", t: 30, text: "Jeudi 8h30 c'est parfait." },
      { role: "tool", t: 32, text: "RDV créé dans le DMS", tool: { name: "book_appointment", input: { slot: "Jeudi 8h30", service: "Révision constructeur" }, result: { confirmation: "RDV-48211", advisor: "Karim Benali" } } },
      { role: "agent", t: 34, text: "C'est noté : jeudi 8h30 avec Karim Benali, et un véhicule de courtoisie vous attendra. Vous allez recevoir un SMS de confirmation. Puis-je faire autre chose pour vous ?" },
      { role: "caller", t: 45, text: "Non c'est tout, merci beaucoup !" },
      { role: "agent", t: 47, text: "Avec plaisir, très bonne journée madame Garnier." },
    ],
  },
  {
    id: "call_8M1P",
    minutesAgo: 38,
    durationSec: 212,
    direction: "inbound",
    caller: { name: "Thomas Lefèvre", phone: "07 81 22 09 64", known: false },
    siteId: "lyon-est",
    language: "fr",
    intent: "essai",
    outcome: "lead_cree",
    sentiment: "positif",
    afterHours: false,
    csat: 5,
    leadId: "lead_2001",
    summary:
      "Prospect intéressé par une Peugeot E-3008 GT, budget ~45 k€, reprise d'une Golf 7 de 2018. Essai planifié samedi 10h avec Inès Fontaine. Lead chaud (score 86).",
    extracted: { Intérêt: "Peugeot E-3008 GT", Budget: "≈ 45 000 €", Reprise: "VW Golf 7 · 2018 · 98 000 km", Financement: "LOA à étudier", Essai: "Samedi 10h" },
    transcript: [
      { role: "agent", t: 0, text: "Mistral Automobiles bonjour, je suis Léa. Comment puis-je vous aider ?" },
      { role: "caller", t: 4, text: "Bonjour, j'ai vu la nouvelle E-3008 sur votre site, j'aimerais l'essayer." },
      { role: "agent", t: 9, text: "Excellent choix ! Vous pensez plutôt à la finition Allure ou GT ? Et c'est pour un usage plutôt urbain ou avec de longs trajets ?" },
      { role: "caller", t: 17, text: "La GT. Je fais Lyon-Grenoble deux fois par semaine." },
      { role: "agent", t: 23, text: "La version grande autonomie serait idéale pour ça, jusqu'à 700 kilomètres. Avez-vous un véhicule à faire reprendre ?" },
      { role: "caller", t: 31, text: "Oui, une Golf 7 de 2018, à peu près 98 000 kilomètres." },
      { role: "tool", t: 36, text: "Créneaux d'essai E-3008 GT", tool: { name: "check_availability", input: { service: "Essai E-3008 GT" }, result: { slots: ["Samedi 10h00", "Samedi 14h30"] } } },
      { role: "agent", t: 38, text: "Je peux vous proposer un essai samedi à 10h ou à 14h30, et nous estimerons votre Golf sur place. Lequel vous convient ?" },
      { role: "caller", t: 46, text: "Samedi 10h." },
      { role: "tool", t: 48, text: "Lead créé et assigné", tool: { name: "create_lead", input: { interest: "VN", vehicle: "E-3008 GT", trade_in: "Golf 7 2018" }, result: { lead_id: "lead_2001", assignee: "Inès Fontaine", score: 86 } } },
      { role: "agent", t: 50, text: "Parfait, Inès Fontaine vous attendra samedi à 10h. Pouvez-vous me confirmer votre nom et un e-mail pour vous envoyer la fiche du véhicule ?" },
      { role: "caller", t: 58, text: "Thomas Lefèvre, thomas.lefevre@gmail.com." },
      { role: "agent", t: 66, text: "Merci monsieur Lefèvre, c'est envoyé. À samedi !" },
    ],
  },
  {
    id: "call_3R7D",
    minutesAgo: 64,
    durationSec: 71,
    direction: "inbound",
    caller: { name: "Ahmed Haddad", phone: "06 45 90 12 77", known: true },
    siteId: "villeurbanne",
    language: "fr",
    intent: "suivi_reparation",
    outcome: "info_donnee",
    sentiment: "positif",
    afterHours: false,
    vehicle: { make: "Toyota", model: "C-HR", plate: "FX-219-PB", year: 2020 },
    summary: "Client demande si son C-HR est prêt. Intervention terminée, véhicule disponible dès 17h. Facture 412,60 € communiquée.",
    extracted: { Véhicule: "Toyota C-HR · FX-219-PB", Statut: "Terminé — contrôle qualité OK", Disponible: "Aujourd'hui 17h", Montant: "412,60 €" },
    transcript: [
      { role: "agent", t: 0, text: "Mistral Automobiles Villeurbanne bonjour, je suis Léa. Comment puis-je vous aider ?" },
      { role: "caller", t: 4, text: "Oui bonjour, c'est pour savoir si ma voiture est prête, un C-HR." },
      { role: "tool", t: 7, text: "Statut OR dans le DMS", tool: { name: "get_repair_status", input: { plate: "FX-219-PB" }, result: { status: "Terminé", ready_at: "17:00", amount: "412,60 €" } } },
      { role: "agent", t: 9, text: "Bonne nouvelle monsieur Haddad : l'intervention sur votre C-HR est terminée et le contrôle qualité est validé. Vous pouvez le récupérer à partir de 17h. Le montant est de 412 euros 60." },
      { role: "caller", t: 24, text: "Super, je passe vers 18h alors." },
      { role: "agent", t: 27, text: "Parfait, l'atelier ferme à 18h30. Je préviens la réception de votre passage. Bonne fin de journée !" },
    ],
  },
  {
    id: "call_5T9A",
    minutesAgo: 60 * 11 + 13,
    durationSec: 133,
    direction: "inbound",
    caller: { name: "James Whitaker", phone: "+44 7700 900461", known: false },
    siteId: "lyon-est",
    language: "en",
    intent: "rdv_atelier",
    outcome: "rdv_pris",
    sentiment: "neutre",
    afterHours: true,
    csat: 4,
    vehicle: { make: "Citroën", model: "C5 Aircross", plate: "Location", year: 2023 },
    appointmentId: "apt_1002",
    summary: "Touriste britannique (véhicule de location), voyant moteur allumé. Appel à 22h47. Diagnostic réservé demain 8h, consignes de sécurité données.",
    extracted: { Langue: "Anglais", Problème: "Voyant moteur orange", Créneau: "Demain 8h00", Service: "Diagnostic électronique" },
    transcript: [
      { role: "agent", t: 0, text: "Mistral Automobiles, good evening. I'm Léa, the dealership's assistant. How can I help?" },
      { role: "caller", t: 4, text: "Hi, I'm driving a rental C5 Aircross and an orange engine light just came on. Is it safe to drive?" },
      { role: "agent", t: 11, text: "An orange engine light usually isn't an emergency, but I'd avoid long trips. If it starts flashing or you notice a loss of power, please stop safely. Would you like a diagnostic first thing tomorrow?" },
      { role: "caller", t: 24, text: "Yes please, as early as possible." },
      { role: "tool", t: 26, text: "Créneaux diagnostic", tool: { name: "check_availability", input: { service: "Diagnostic électronique", date: "tomorrow" }, result: { slots: ["08:00", "09:30"] } } },
      { role: "tool", t: 30, text: "RDV créé", tool: { name: "book_appointment", input: { slot: "08:00", service: "Diagnostic électronique" }, result: { confirmation: "RDV-48214" } } },
      { role: "agent", t: 31, text: "You're booked tomorrow at 8 a.m. at 48 avenue Jean Mermoz in Lyon. I've sent the address by text. Anything else?" },
      { role: "caller", t: 40, text: "That's great, thanks a lot." },
    ],
  },
  {
    id: "call_2B6F",
    minutesAgo: 60 * 3 + 2,
    durationSec: 98,
    direction: "inbound",
    caller: { phone: "06 77 31 40 02", known: false },
    siteId: "lyon-est",
    language: "fr",
    intent: "pieces",
    outcome: "transfere",
    sentiment: "neutre",
    afterHours: false,
    transferredTo: "pieces",
    summary: "Demande de plaquettes avant pour Clio IV 1.5 dCi. Référence pré-qualifiée puis transfert au magasin pièces avec fiche contexte.",
    extracted: { Pièce: "Plaquettes de frein avant", Véhicule: "Renault Clio IV 1.5 dCi 2016", Transfert: "Magasin pièces" },
    transcript: [
      { role: "agent", t: 0, text: "Mistral Automobiles bonjour, je suis Léa. Comment puis-je vous aider ?" },
      { role: "caller", t: 3, text: "Je cherche des plaquettes avant pour une Clio 4, vous en avez ?" },
      { role: "agent", t: 8, text: "Je vais vous mettre en relation avec le magasin pièces. Pour gagner du temps, c'est bien une Clio 4 diesel 1.5 dCi ? De quelle année ?" },
      { role: "caller", t: 16, text: "Oui, 2016." },
      { role: "tool", t: 18, text: "Transfert chaud vers le magasin pièces", tool: { name: "transfer_call", input: { department: "pieces", reason: "Plaquettes AV Clio IV 1.5 dCi 2016" }, result: { status: "connected", agent: "Magasin pièces" } } },
      { role: "agent", t: 19, text: "Merci, je vous transfère à Franck du magasin pièces, il a déjà toutes les informations. Bonne journée !" },
    ],
  },
  {
    id: "call_9K4C",
    minutesAgo: 60 * 26 + 40,
    durationSec: 246,
    direction: "inbound",
    caller: { name: "Martine Dupuis", phone: "06 03 55 18 90", known: true },
    siteId: "lyon-est",
    language: "fr",
    intent: "reclamation",
    outcome: "rappel_programme",
    sentiment: "negatif",
    afterHours: false,
    summary:
      "Cliente mécontente : facture supérieure au devis (+86 €) sans appel préalable. Écoute, reformulation, excuses. Rappel du chef d'atelier programmé aujourd'hui avant 17h. Alerte envoyée au responsable après-vente.",
    extracted: { Motif: "Écart devis / facture (+86 €)", Priorité: "Haute", Rappel: "Chef d'atelier · avant 17h", Alerte: "Responsable APV notifié" },
    transcript: [
      { role: "agent", t: 0, text: "Mistral Automobiles bonjour, je suis Léa. Comment puis-je vous aider ?" },
      { role: "caller", t: 4, text: "Oui, je suis très mécontente. On m'a facturé 86 euros de plus que le devis et personne ne m'a appelée !" },
      { role: "agent", t: 12, text: "Je comprends tout à fait votre agacement, madame Dupuis, et je suis désolée. Un dépassement de devis doit toujours vous être soumis avant. Je vais faire en sorte que cela soit traité en priorité." },
      { role: "caller", t: 26, text: "J'espère bien. Je veux parler à un responsable." },
      { role: "tool", t: 29, text: "Rappel prioritaire programmé", tool: { name: "schedule_callback", input: { department: "apres_vente", priority: "high", reason: "Écart devis/facture +86 €" }, result: { callback: "Aujourd'hui avant 17h", owner: "Chef d'atelier" } } },
      { role: "agent", t: 31, text: "Le chef d'atelier vous rappellera aujourd'hui avant 17h, et j'ai transmis votre dossier au responsable après-vente avec la facture et le devis. Est-ce que ce numéro est le bon pour vous joindre ?" },
      { role: "caller", t: 44, text: "Oui. Merci, au moins vous m'écoutez." },
    ],
  },
  {
    id: "call_4V8N",
    minutesAgo: 60 * 30 + 5,
    durationSec: 187,
    direction: "inbound",
    caller: { name: "Lucía Fernández", phone: "06 98 12 63 45", known: false },
    siteId: "villeurbanne",
    language: "es",
    intent: "rdv_atelier",
    outcome: "rdv_pris",
    sentiment: "positif",
    afterHours: false,
    csat: 5,
    vehicle: { make: "Toyota", model: "Yaris Cross", year: 2022 },
    appointmentId: "apt_1003",
    summary: "Appel en espagnol : montage de 4 pneus hiver sur Yaris Cross. RDV pris mercredi 14h. Pneus commandés via le magasin.",
    extracted: { Langue: "Espagnol", Service: "Pneumatiques ×4 (hiver)", Créneau: "Mercredi 14h00" },
    transcript: [
      { role: "agent", t: 0, text: "Mistral Automobiles buenos días, soy Léa. ¿En qué puedo ayudarle?" },
      { role: "caller", t: 4, text: "Hola, quería montar neumáticos de invierno en mi Yaris Cross." },
      { role: "agent", t: 9, text: "¡Claro! ¿Necesita también los neumáticos o ya los tiene?" },
      { role: "caller", t: 13, text: "No los tengo, necesito cuatro." },
      { role: "tool", t: 15, text: "Créneaux pneumatiques", tool: { name: "check_availability", input: { service: "Pneumatiques" }, result: { slots: ["Miércoles 14:00", "Jueves 10:30"] } } },
      { role: "agent", t: 17, text: "Puedo proponerle el miércoles a las 14:00 o el jueves a las 10:30. Pediremos los neumáticos para esa fecha." },
      { role: "caller", t: 25, text: "El miércoles, perfecto." },
    ],
  },
  {
    id: "call_6H3E",
    minutesAgo: 60 * 50 + 21,
    durationSec: 164,
    direction: "inbound",
    caller: { name: "Kevin Marchand", phone: "07 66 20 13 98", known: false },
    siteId: "bron",
    language: "fr",
    intent: "achat_vo",
    outcome: "lead_cree",
    sentiment: "positif",
    afterHours: true,
    leadId: "lead_2002",
    summary: "Appel à 21h12 pour une Toyota Yaris hybride 2021 vue sur Leboncoin. Disponibilité confirmée, visite programmée demain 18h. Lead VO assigné à Marc Dubois.",
    extracted: { Annonce: "Toyota Yaris Hybride 2021 · 32 000 km · 17 490 €", Visite: "Demain 18h00", Financement: "Demande de simulation" },
    transcript: [
      { role: "agent", t: 0, text: "Mistral Occasions bonsoir, je suis Léa. Comment puis-je vous aider ?" },
      { role: "caller", t: 4, text: "Bonsoir, j'appelle pour la Yaris hybride de 2021 sur Leboncoin, elle est toujours dispo ?" },
      { role: "tool", t: 8, text: "Stock VO", tool: { name: "search_inventory", input: { query: "Toyota Yaris hybride 2021" }, result: { found: true, price: "17 490 €", mileage: "32 000 km" } } },
      { role: "agent", t: 10, text: "Oui, elle est toujours disponible : 32 000 kilomètres, 17 490 euros, garantie 12 mois. Voulez-vous venir la voir ?" },
    ],
  },
  {
    id: "call_1X5Z",
    minutesAgo: 60 * 52,
    durationSec: 122,
    direction: "outbound",
    caller: { name: "Patrick Roche", phone: "06 21 73 85 40", known: true },
    siteId: "lyon-est",
    language: "fr",
    intent: "rdv_atelier",
    outcome: "rdv_pris",
    sentiment: "positif",
    afterHours: false,
    csat: 5,
    vehicle: { make: "Citroën", model: "C4 PureTech", plate: "FP-604-KM", year: 2019 },
    appointmentId: "apt_1004",
    summary: "Campagne « rappel entretien » : échéance de révision atteinte. Client recontacté, RDV pris lundi 9h15 + pré-contrôle technique offert.",
    extracted: { Campagne: "Rappel entretien · octobre", Créneau: "Lundi 9h15", "Upsell": "Pré-contrôle technique" },
    transcript: [
      { role: "agent", t: 0, text: "Bonjour monsieur Roche, ici Léa de Mistral Automobiles. Je vous appelle car votre C4 arrive à l'échéance de sa révision. Avez-vous deux minutes ?" },
      { role: "caller", t: 9, text: "Ah oui, c'est vrai. Oui allez-y." },
    ],
  },
  {
    id: "call_0J2W",
    minutesAgo: 60 * 75,
    durationSec: 95,
    direction: "inbound",
    caller: { name: "Sarah Benhamou", phone: "06 30 47 91 26", known: false },
    siteId: "lyon-est",
    language: "fr",
    intent: "carrosserie",
    outcome: "rdv_pris",
    sentiment: "neutre",
    afterHours: false,
    vehicle: { make: "Peugeot", model: "208", year: 2022 },
    appointmentId: "apt_1005",
    summary: "Accrochage sur parking (pare-choc arrière). Expertise carrosserie gratuite réservée mardi 11h. Rappel : apporter le constat et la carte grise.",
    extracted: { Dommage: "Pare-choc arrière", Assurance: "MAIF", Créneau: "Mardi 11h00" },
    transcript: [
      { role: "agent", t: 0, text: "Mistral Automobiles bonjour, je suis Léa. Comment puis-je vous aider ?" },
      { role: "caller", t: 3, text: "Bonjour, on m'a embouti le pare-choc arrière de ma 208, je voudrais un devis." },
    ],
  },
];

export function getDemoCalls(now = new Date()): CallRecord[] {
  return SEEDS.map(({ minutesAgo, ...c }) => ({
    ...c,
    startedAt: new Date(now.getTime() - minutesAgo * 60_000).toISOString(),
  }));
}
